In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
pwd

'C:\\Users\\Akshay Gupta\\Machine Learning a-z Udemy'

In [3]:
ls

 Volume in drive C is Windows
 Volume Serial Number is EAFE-F87C

 Directory of C:\Users\Akshay Gupta\Machine Learning a-z Udemy

14-02-2019  09:52    <DIR>          .
14-02-2019  09:52    <DIR>          ..
01-11-2017  11:37             6,148 .DS_Store
14-02-2019  09:52    <DIR>          .ipynb_checkpoints
13-02-2019  22:45            22,151 Missing Data.ipynb
13-02-2019  16:27    <DIR>          Part 0 - Welcome to Machine Learning A-Z
13-02-2019  16:27    <DIR>          Part 1 - Data Preprocessing
13-02-2019  16:27    <DIR>          Part 10 - Model Selection & Boosting
13-02-2019  16:27    <DIR>          Part 2 - Regression
13-02-2019  16:27    <DIR>          Part 3 - Classification
13-02-2019  16:27    <DIR>          Part 4 - Clustering
13-02-2019  16:27    <DIR>          Part 5 - Association Rule Learning
13-02-2019  16:27    <DIR>          Part 6 - Reinforcement Learning
13-02-2019  16:27    <DIR>          Part 7 - Natural Language Processing
13-02-2019  16:27    <DIR>          Par

In [4]:
cd Part 1 - Data Preprocessing

C:\Users\Akshay Gupta\Machine Learning a-z Udemy\Part 1 - Data Preprocessing


In [5]:
pwd

'C:\\Users\\Akshay Gupta\\Machine Learning a-z Udemy\\Part 1 - Data Preprocessing'

In [6]:
data=pd.read_csv('Data.csv')

In [7]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [8]:
X=data.iloc[:,:-1].values
#all the rows and all rows except last column
#Matrix for features
#Independent Variable Vector

In [9]:
y=data.iloc[:,3].values
#Dependent Variable Vector

In [10]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# HANDLENING MISSING DATA
# REPLACING BY MEAN VALUE

In [11]:
from sklearn.impute import SimpleImputer

In [44]:
imputer=SimpleImputer(missing_values='NaN',strategy='mean')

TypeError: 'SimpleImputer' object is not callable

In [13]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# 2nd and 3rd Column contains NaN Values

In [14]:
imputer=SimpleImputer(missing_values='NaN', strategy='mean')

class sklearn.impute.SimpleImputer(missing_values=nan, strategy=’mean’, fill_value=None, verbose=0, copy=True)

Instead of mean, we can write 'median' or 'most_frequent'

In [43]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

# <font size="50"><font color="red"> 015 Categorical Data: - </font>

In [16]:
#Encode text into integer #Country and Purchased

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
#Let object for LabelEncoder class be = labelencoder

In [19]:
labelencoder_X=LabelEncoder()

In [20]:
labelencoder_X.fit_transform(X[:,0])

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0])

In [21]:
X[:,0]=_

In [22]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [23]:
#But here numbers are misleading. So we need one more class to sort this problem

In [24]:
from sklearn.preprocessing import OneHotEncoder

In [25]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])
print(X)
print(X.shape)

[[0 44.0 72000.0]
 [2 27.0 48000.0]
 [1 30.0 54000.0]
 [2 38.0 61000.0]
 [1 40.0 nan]
 [0 35.0 58000.0]
 [2 nan 52000.0]
 [0 48.0 79000.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]
(10, 3)


In [29]:
#onehotencoder = OneHotEncoder()
#X[:, 0] = onehotencoder.fit_transform(X[:, 0]).toarray()
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [30]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [31]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, nan],
       [0, 35.0, 58000.0],
       [2, nan, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

# Making Machine Learning Models
## Splitting Data Sets: -

In [33]:
from sklearn.model_selection import train_test_split

In [37]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)  #Split dataset
#into train and test data
#test_size=0.2 ==20%.
#random_state is set to 0 here to exactly match the results with the video
#good choice of random_state is 42

## Feature Scaling: -

It is being done because in our data Age and Salary are very differnt in terms of range (Age is in between 30-50 and Salary is between 50k to 80k)  Salary has much wider range

This leads to problem because most of the machine learning models are based on 'Euclidean Distance' Strategy. In our case, the euclidean distance would be dominated by salary.

So we have to make them in same range

### Even if machine learning model is not based on Euclidean Distance, then too we have to do feature scaling so as to ensure our algorithm converge must faster

In [46]:
from sklearn.preprocessing import StandardScaler

In [47]:
# Let's define object for StandardScaler class is sc_X

sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

#in training set we have to first fit the data and then transform it
#in test set we have to just transform the data, as it was fitted in training phase itself