In [1]:
# importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

#importing the dataset
dataset=pd.read_csv('50_Startups.csv')

#Setting Matrix of Features(Independent Variable) and Dependent Variable
#We want are model to predict profit === it will be dependent variable
#Others will be independet varialble
X=dataset.iloc[:,:-1].values ##take all rows and all columns except last column
y=dataset.iloc[:,4].values

# Splitting the dataset into training and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)  #Split dataset
#into train and test data
#test_size=0.2 ==20%.
#random_state is set to 0 here to exactly match the results with the video
#good choice of random_state is 42

In [2]:
dataset.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
 dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [4]:
X

array([[165349.2, 136897.8, 471784.1, 'New York'],
       [162597.7, 151377.59, 443898.53, 'California'],
       [153441.51, 101145.55, 407934.54, 'Florida'],
       [144372.41, 118671.85, 383199.62, 'New York'],
       [142107.34, 91391.77, 366168.42, 'Florida'],
       [131876.9, 99814.71, 362861.36, 'New York'],
       [134615.46, 147198.87, 127716.82, 'California'],
       [130298.13, 145530.06, 323876.68, 'Florida'],
       [120542.52, 148718.95, 311613.29, 'New York'],
       [123334.88, 108679.17, 304981.62, 'California'],
       [101913.08, 110594.11, 229160.95, 'Florida'],
       [100671.96, 91790.61, 249744.55, 'California'],
       [93863.75, 127320.38, 249839.44, 'Florida'],
       [91992.39, 135495.07, 252664.93, 'California'],
       [119943.24, 156547.42, 256512.92, 'Florida'],
       [114523.61, 122616.84, 261776.23, 'New York'],
       [78013.11, 121597.55, 264346.06, 'California'],
       [94657.16, 145077.58, 282574.31, 'New York'],
       [91749.16, 114175.79, 29491

In [5]:
y

array([192261.83, 191792.06, 191050.39, 182901.99, 166187.94, 156991.12,
       156122.51, 155752.6 , 152211.77, 149759.96, 146121.95, 144259.4 ,
       141585.52, 134307.35, 132602.65, 129917.04, 126992.93, 125370.37,
       124266.9 , 122776.86, 118474.03, 111313.02, 110352.25, 108733.99,
       108552.04, 107404.34, 105733.54, 105008.31, 103282.38, 101004.64,
        99937.59,  97483.56,  97427.84,  96778.92,  96712.8 ,  96479.51,
        90708.19,  89949.14,  81229.06,  81005.76,  78239.91,  77798.83,
        71498.49,  69758.98,  65200.33,  64926.08,  49490.75,  42559.73,
        35673.41,  14681.4 ])

In [6]:
#Categorical Variable must be encoded here == State Variable
#encode the 4th column of X

# Apply one-hot encoding to the “weather” variable
X_encoded = pd.get_dummies(dataset['State'])
X_encoded

California  Florida  New York
0            0        0         1
1            1        0         0
2            0        1         0
3            0        0         1
4            0        1         0
5            0        0         1
6            1        0         0
7            0        1         0
8            0        0         1
9            1        0         0
10           0        1         0
11           1        0         0
12           0        1         0
13           1        0         0
14           0        1         0
15           0        0         1
16           1        0         0
17           0        0         1
18           0        1         0
19           0        0         1
20           1        0         0
21           0        0         1
22           0        1         0
23           0        1         0
24           0        0         1
25           1        0         0
26           0        1         0
27           0        0         1
28           0        1         0
29           0        0         1
30           0        1         0
31           0        0         1
32           1        0         0
33           0        1         0
34           1        0         0
35           0        0         1
36           0        1         0
37           1        0         0
38           0        0         1
39           1        0         0
40           1        0         0
41           0        1         0
42           1        0         0
43           0        0         1
44           1        0         0
45           0        0         1
46           0        1         0
47           1        0         0
48           0        0         1
49           1        0         0

In [7]:
X=np.append(X,X_encoded,1)

In [8]:
X=np.delete(X,3,1)

In [9]:
X

array([[165349.2, 136897.8, 471784.1, 0, 0, 1],
       [162597.7, 151377.59, 443898.53, 1, 0, 0],
       [153441.51, 101145.55, 407934.54, 0, 1, 0],
       [144372.41, 118671.85, 383199.62, 0, 0, 1],
       [142107.34, 91391.77, 366168.42, 0, 1, 0],
       [131876.9, 99814.71, 362861.36, 0, 0, 1],
       [134615.46, 147198.87, 127716.82, 1, 0, 0],
       [130298.13, 145530.06, 323876.68, 0, 1, 0],
       [120542.52, 148718.95, 311613.29, 0, 0, 1],
       [123334.88, 108679.17, 304981.62, 1, 0, 0],
       [101913.08, 110594.11, 229160.95, 0, 1, 0],
       [100671.96, 91790.61, 249744.55, 1, 0, 0],
       [93863.75, 127320.38, 249839.44, 0, 1, 0],
       [91992.39, 135495.07, 252664.93, 1, 0, 0],
       [119943.24, 156547.42, 256512.92, 0, 1, 0],
       [114523.61, 122616.84, 261776.23, 0, 0, 1],
       [78013.11, 121597.55, 264346.06, 1, 0, 0],
       [94657.16, 145077.58, 282574.31, 0, 0, 1],
       [91749.16, 114175.79, 294919.57, 0, 1, 0],
       [86419.7, 153514.11, 0.0, 0, 0, 1],
 

## Avioiding Dummy Variable Trap

In [10]:
X=X[:,1:] ##Here we just removed first column from X
## As we have to remove atleast

## We need not do it always, as Library for regression will automatically take care of dummy variable

# Train - Test Split

In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [12]:
X_train.shape

(40, 5)

In [13]:
X_test.shape

(10, 5)

## Fitting data to Linear Regression Model

In [14]:
from sklearn.linear_model import LinearRegression

In [15]:
regressor=LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [16]:
##Predicting test set results

y_pred=regressor.predict(X_test)

In [17]:
y_pred

array([106577.99626347, 105343.13679761, 102277.71300215,  75479.98875117,
       141370.81457966, 155922.74625991,  88638.20542027, 102659.16409964,
       125449.05313433, 127073.25530139])

In [18]:
y_test

array([103282.38, 144259.4 , 146121.95,  77798.83, 191050.39, 105008.31,
        81229.06,  97483.56, 110352.25, 166187.94])

# <font color ='red'><font size=10> Backward Elimination


In [19]:
import statsmodels.formula.api as sm

In [20]:
np.ones

<function numpy.core.numeric.ones(shape, dtype=None, order='C')>

In [21]:
x0=np.ones((50,1)).astype(int)

In [22]:
np.append

<function numpy.lib.function_base.append(arr, values, axis=None)>

In [23]:
X=np.append(x0,values=X,axis=1)

In [24]:
X

array([[1, 136897.8, 471784.1, 0, 0, 1],
       [1, 151377.59, 443898.53, 1, 0, 0],
       [1, 101145.55, 407934.54, 0, 1, 0],
       [1, 118671.85, 383199.62, 0, 0, 1],
       [1, 91391.77, 366168.42, 0, 1, 0],
       [1, 99814.71, 362861.36, 0, 0, 1],
       [1, 147198.87, 127716.82, 1, 0, 0],
       [1, 145530.06, 323876.68, 0, 1, 0],
       [1, 148718.95, 311613.29, 0, 0, 1],
       [1, 108679.17, 304981.62, 1, 0, 0],
       [1, 110594.11, 229160.95, 0, 1, 0],
       [1, 91790.61, 249744.55, 1, 0, 0],
       [1, 127320.38, 249839.44, 0, 1, 0],
       [1, 135495.07, 252664.93, 1, 0, 0],
       [1, 156547.42, 256512.92, 0, 1, 0],
       [1, 122616.84, 261776.23, 0, 0, 1],
       [1, 121597.55, 264346.06, 1, 0, 0],
       [1, 145077.58, 282574.31, 0, 0, 1],
       [1, 114175.79, 294919.57, 0, 1, 0],
       [1, 153514.11, 0.0, 0, 0, 1],
       [1, 113867.3, 298664.47, 1, 0, 0],
       [1, 153773.43, 299737.29, 0, 0, 1],
       [1, 122782.75, 303319.26, 0, 1, 0],
       [1, 105751.03, 3

In [25]:
##Creating optimal matrix of feaatures
##Contains only those information that has high impact on profit
X_opt = X[:, [0, 1, 2, 3, 4, 5]]
X_opt
##selected all values initally (in first iteration)

array([[1, 136897.8, 471784.1, 0, 0, 1],
       [1, 151377.59, 443898.53, 1, 0, 0],
       [1, 101145.55, 407934.54, 0, 1, 0],
       [1, 118671.85, 383199.62, 0, 0, 1],
       [1, 91391.77, 366168.42, 0, 1, 0],
       [1, 99814.71, 362861.36, 0, 0, 1],
       [1, 147198.87, 127716.82, 1, 0, 0],
       [1, 145530.06, 323876.68, 0, 1, 0],
       [1, 148718.95, 311613.29, 0, 0, 1],
       [1, 108679.17, 304981.62, 1, 0, 0],
       [1, 110594.11, 229160.95, 0, 1, 0],
       [1, 91790.61, 249744.55, 1, 0, 0],
       [1, 127320.38, 249839.44, 0, 1, 0],
       [1, 135495.07, 252664.93, 1, 0, 0],
       [1, 156547.42, 256512.92, 0, 1, 0],
       [1, 122616.84, 261776.23, 0, 0, 1],
       [1, 121597.55, 264346.06, 1, 0, 0],
       [1, 145077.58, 282574.31, 0, 0, 1],
       [1, 114175.79, 294919.57, 0, 1, 0],
       [1, 153514.11, 0.0, 0, 0, 1],
       [1, 113867.3, 298664.47, 1, 0, 0],
       [1, 153773.43, 299737.29, 0, 0, 1],
       [1, 122782.75, 303319.26, 0, 1, 0],
       [1, 105751.03, 3

In [26]:
print(type(X_opt),X_opt.shape)
print(type(y),y.shape)

<class 'numpy.ndarray'> (50, 6)
<class 'numpy.ndarray'> (50,)


In [27]:
y=y.astype(dtype=np.float64)
X_opt=X_opt.astype(dtype=np.float64)

In [28]:
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()   ##Ordinary Least Square

In [29]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.613
Model:                            OLS   Adj. R-squared:                  0.579
Method:                 Least Squares   F-statistic:                     17.83
Date:                Sun, 17 Feb 2019   Prob (F-statistic):           7.78e-09
Time:                        19:45:02   Log-Likelihood:                -576.91
No. Observations:                  50   AIC:                             1164.
Df Residuals:                      45   BIC:                             1173.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       1.482e+04   1.36e+04      1.091      0.281   -1.25e+04    4.22e+04
x1             0.3239      0.133      2.426      0.019       0.055       0.593
x2             0.2507      0.031      7.997      0.000       0.188       0.314
x3          4214.9699   6660.035      0.633      0.530   -9199.028    1.76e+04
x4          2511.2671   7380.550      0.340      0.735   -1.24e+04    1.74e+04
x5          8090.7324   6855.885      1.180      0.244   -5717.730    2.19e+04
==============================================================================
Omnibus:                        5.729   Durbin-Watson:                   1.266
Prob(Omnibus):                  0.057   Jarque-Bera (JB):                5.349
Skew:                          -0.461   Prob(JB):                       0.0689
Kurtosis:                       4.311   Cond. No.                     3.09e+21
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 3.72e-31. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [30]:
#We have to remove x4
#But it should be removed from X, hence x4 here corresponds to index=5
#Hence we will be removing 'FLORIDA' column
X

array([[1, 136897.8, 471784.1, 0, 0, 1],
       [1, 151377.59, 443898.53, 1, 0, 0],
       [1, 101145.55, 407934.54, 0, 1, 0],
       [1, 118671.85, 383199.62, 0, 0, 1],
       [1, 91391.77, 366168.42, 0, 1, 0],
       [1, 99814.71, 362861.36, 0, 0, 1],
       [1, 147198.87, 127716.82, 1, 0, 0],
       [1, 145530.06, 323876.68, 0, 1, 0],
       [1, 148718.95, 311613.29, 0, 0, 1],
       [1, 108679.17, 304981.62, 1, 0, 0],
       [1, 110594.11, 229160.95, 0, 1, 0],
       [1, 91790.61, 249744.55, 1, 0, 0],
       [1, 127320.38, 249839.44, 0, 1, 0],
       [1, 135495.07, 252664.93, 1, 0, 0],
       [1, 156547.42, 256512.92, 0, 1, 0],
       [1, 122616.84, 261776.23, 0, 0, 1],
       [1, 121597.55, 264346.06, 1, 0, 0],
       [1, 145077.58, 282574.31, 0, 0, 1],
       [1, 114175.79, 294919.57, 0, 1, 0],
       [1, 153514.11, 0.0, 0, 0, 1],
       [1, 113867.3, 298664.47, 1, 0, 0],
       [1, 153773.43, 299737.29, 0, 0, 1],
       [1, 122782.75, 303319.26, 0, 1, 0],
       [1, 105751.03, 3

In [31]:
##Remove x3 as it has p value>SL
X_opt=X[:,[0,1,2,3,4]]
X_opt=X_opt.astype(np.float64)
y=y.astype(np.float64)

In [32]:
regressor_OLS=sm.OLS(endog=y,exog=X_opt).fit()   ##Ordinary Least Square

In [33]:
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.613
Model:                            OLS   Adj. R-squared:                  0.579
Method:                 Least Squares   F-statistic:                     17.83
Date:                Sun, 17 Feb 2019   Prob (F-statistic):           7.78e-09
Time:                        19:45:02   Log-Likelihood:                -576.91
No. Observations:                  50   AIC:                             1164.
Df Residuals:                      45   BIC:                             1173.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.291e+04   1.88e+04      1.220      0.229   -1.49e+04    6.07e+04
x1             0.3239      0.133      2.426      0.019       0.055       0.593
x2             0.2507      0.031      7.997      0.000       0.188       0.314
x3         -3875.7625   9002.603     -0.431      0.669    -2.2e+04    1.43e+04
x4         -5579.4653   9207.095     -0.606      0.548   -2.41e+04     1.3e+04
==============================================================================
Omnibus:                        5.729   Durbin-Watson:                   1.266
Prob(Omnibus):                  0.057   Jarque-Bera (JB):                5.349
Skew:                          -0.461   Prob(JB):                       0.0689
Kurtosis:                       4.311   Cond. No.                     1.38e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.38e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [34]:
##Remove x3 as it has p value>SL
#Hence we will be removing 'CALIFORNIA' column
X_opt=X[:,[0,1,2,4]]
X_opt=X_opt.astype(np.float64)

In [35]:
regressor_OLS=sm.OLS(y,X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.612
Model:                            OLS   Adj. R-squared:                  0.586
Method:                 Least Squares   F-statistic:                     24.14
Date:                Sun, 17 Feb 2019   Prob (F-statistic):           1.57e-09
Time:                        19:45:03   Log-Likelihood:                -577.02
No. Observations:                  50   AIC:                             1162.
Df Residuals:                      46   BIC:                             1170.
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.066e+04   1.79e+04      1.156      0.254   -1.53e+04    5.66e+04
x1             0.3247      0.132      2.455      0.018       0.058       0.591
x2             0.2518      0.031      8.130      0.000       0.189       0.314
x3         -3699.6258   8033.729     -0.461      0.647   -1.99e+04    1.25e+04
==============================================================================
Omnibus:                        5.809   Durbin-Watson:                   1.281
Prob(Omnibus):                  0.055   Jarque-Bera (JB):                5.344
Skew:                          -0.481   Prob(JB):                       0.0691
Kurtosis:                       4.280   Cond. No.                     1.30e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.3e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [36]:
#NOW x3 SHOULD BE REMOVED
#x3 corresponds to 'NEW YORK'
X_opt=X[:,[0,1,2]]
X_opt=X_opt.astype(np.float64)

In [37]:
regressor_OLS=sm.OLS(y,X_opt).fit()
regressor_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.610
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     36.71
Date:                Sun, 17 Feb 2019   Prob (F-statistic):           2.50e-10
Time:                        19:45:03   Log-Likelihood:                -577.13
No. Observations:                  50   AIC:                             1160.
Df Residuals:                      47   BIC:                             1166.
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       2.022e+04   1.77e+04      1.143      0.259   -1.54e+04    5.58e+04
x1             0.3237      0.131      2.468      0.017       0.060       0.588
x2             0.2488      0.030      8.281      0.000       0.188       0.309
==============================================================================
Omnibus:                        6.584   Durbin-Watson:                   1.279
Prob(Omnibus):                  0.037   Jarque-Bera (JB):                6.524
Skew:                          -0.512   Prob(JB):                       0.0383
Kurtosis:                       4.443   Cond. No.                     1.30e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.3e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""